name: Dry publish binary

on:
  push:
    branches: [ master, 'release/**'  ]
  pull_request:
    branches: [ master, 'release/**'  ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: fwilhe2/setup-kotlin@main
      - run: ./fetch.main.kts
      - uses: actions/upload-artifact@v3
        with:
          name: libclang.dylib
          path: ./tmp/libSDL2.dylib
      - uses: actions/upload-artifact@v3
        with:
          name: headers.zip
          path: ./tmp/headers.zip